### ISSUE TITLE
Village Houses bug

### ISSUE THREAD

**Issue by SpaceWace** [Danial-Movahed/Unity-Car-Game#5]
#bug

- House under ground!
- No collider for stone and road of houses!

![Proof_1](https://user-images.githubusercontent.com/87063443/158811159-8119e5fd-eced-4202-ad76-28ab2f5068d9.png)

**Comment by SpaceWace** [comment]
Special thanks to @SpaceWace for his reporting!

**Comment by Danial-Movahed** [comment]
Fixed
